typedef float RowType[20];
typedef RowType TemperatureMesh[20];

interface TemperatureDataInterface
{
	long  randomWalk( 	inout TemperatureMesh mesh,
				in    unsigned long   row, in unsigned long column);
};
