typedef float RowType[50];
typedef RowType TemperatureMesh[50];

interface TemperatureDataInterface
{
	long  randomWalk( 	inout TemperatureMesh mesh,
				in    unsigned long   row, in unsigned long column);
};
